# Generated by Django 6.0.8 on 2026-09-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('send_hour', models.PositiveIntegerField(default=9, help_text='Hour of day (0-23) to send email')),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_report', to='websites.website')),
            ],
        ),
    ]
