# Generated by Django 6.1.1 on 2026-09-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('websites', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='websites.website'),
        ),
    ]
