# Generated by Django 6.0.8 on 2026-10-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_visitor_website'),
        ('websites', '0003_emailreportsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='websites.website')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['website', 'name'], name='analytics_e_website_ae73b4_idx'), models.Index(fields=['website', 'timestamp'], name='analytics_e_website_d74efd_idx')],
            },
        ),
    ]
